[project]
name = "ai-cli"
version = "0.2.0"
description = "A simplified user-friendly interface to running AI enabled jobs from the command line."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.68",
    "langchain-community>=0.3.31",
    "langchain-huggingface>=0.3.1",
    "langchain-mcp-adapters>=0.1.11",
    "langchain-ollama>=0.3.10",
    "langgraph>=0.6.10",
    "pika>=1.3.2",
    "pyyaml-include>=2.2",
    "rich>=14.2.0",
    "sentence-transformers>=2.7.0",
    "transformers>=4.51.0",
]

[dependency-groups]
dev = []
