
services:
  minio:
    image: quay.io/minio/aistor/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001" 
    volumes:
      - C:\minio\data:/mnt/data # Persist data to a local directory
      - C:\minio\certs:/etc/minio/certs
      - C:\minio\minio.license:/minio.license
    environment:
      MINIO_ROOT_USER: "miniadmin" # Change this
      MINIO_ROOT_PASSWORD: "miniosecretpassword" # Change this secure password
    command: server --console-address :9001 /mnt/data --license /minio.license
    restart: always
