# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
# This is an ai-cli.py config file exmaple
# For running ai-cli.py with a local RabbitMQ
# It runs a single workflow
no_banner: True

# the verbosity of the client
verbose: 0

# the role for this client to use
role: "hybrid"

# the queue backend to use
# This assumes RabbitMQ is using credentials guest:guest on localhost on the default port and exchange /.
queue_backend: "rabbitmq"
queue_backend_options:
  url: "amqp://guest:guest@localhost:5672/%2F"

# any workflows we should run
workflow:
 - "workflows/example-invoke-llm-pirate.yaml"

# should we wait for the result from any submitted job.
wait_for_result: true
# should we open an interactive session (show output and wait for additional input)
interactive: false

# this breaks some seperation for usability.
# I think it is useful to be able to pass the system and user prompts on the CLI for testing etc.
# so this is here too even though it can / should be in a workflow?
prompt:
  # additional llm system prompt
  system: "Wrap each response with a random emoji."
  # additional llm user prompt (optional)
  user: ""
