# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
---
# This is an ai-cli.py config file exmaple
# For running ai-cli.py with local shared memeory queue
# It runs a single workflow
no_banner: True

# the verbosity of the client
verbose: 0

# the role for this client to use
role: "hybrid"

# the queue backend to use
# the default is 'none', which is a local-only, non-shared, in-memory queue.
queue_backend: "none"

# any workflows that should be run
workflow:
 - "workflows/example-invoke-llm-pirate.yaml"

# this breaks some seperation for usability.
# I think it is useful to be able to pass the system and user prompts on the CLI for testing etc.
# so this is here too even though it can / should be in a workflow?
prompt:
  # additional llm system prompt
  system: "Wrap each response with a random emoji."
  # additional llm user prompt (optional)
  user: ""
